name: Déploiement Automatique Portfolio AWS

on:
  push:
    branches:
      - main  # Le déploiement se lance quand tu "push" sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v3

    - name: Configurer les identifiants AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3  # Vérifie bien que c'est ta région (Paris)

    - name: Envoyer les fichiers vers S3
      run: |
        aws s3 sync . s3://NOM-DE-TON-BUCKET --exclude ".git*" --delete